package indi.mybatis.flying.statics;

public enum KeyGeneratorType {
	/** Generate by UUID */
	uuid,
	/** Generated by UUID without a horizontal line */
	uuid_no_line,
	/** Timestamp that is accurate to millisecond */
	millisecond,
	/** The simple prototype of snowflake algorithm, for reference only */
	snowflake,
	/** User personalization handler */
	custom,
}
